install.packages('GGally')
install.packages('cvTools')
library(GGally)
library(cvTools)

dataRep<- data.frame(RepSenators)
dataDem <- data.frame(DemSenators)
#dataInd <- data.frame(IndSenators)

dataRep<- dataRep[,1:12]
#Set all of the Republicans' party to 1
dataRep$party = 1

dataDem$party=0
data<- data.frame(rbind(dataRep, dataDem))

wordCounter <- function(invec, word, ...) {
  vapply(regmatches(invec, gregexpr(word, invec, ...)), length, 1L)
}

#------------------------keyword start----------------------------------------------
#care foundation
data$suffer <- wordCounter(data$text, "suffer", ignore.case=TRUE)
data$care <- wordCounter(data$text, "care", ignore.case=TRUE)
hurt <- wordCounter(data$text, "hurt", ignore.case=TRUE)
harm <- wordCounter(data$text, "harm", ignore.case=TRUE)
data$harm <- hurt+harm
data$vulnerable <- wordCounter(data$text, "vulnerable", ignore.case=TRUE)
data$help <- wordCounter(data$text, "help", ignore.case=TRUE)
data$protect <- wordCounter(data$text, "protect", ignore.case=TRUE)
data$mother <- wordCounter(data$text, "mother", ignore.case=TRUE)
data$pity <- wordCounter(data$text, "pity", ignore.case=TRUE)
data$mercy <- wordCounter(data$text, "mercy", ignore.case=TRUE)
data$humane <- wordCounter(data$text, "humane", ignore.case=TRUE)
data$condolence <- wordCounter(data$text, "condolence", ignore.case=TRUE)
data$generous <- wordCounter(data$text, "generous", ignore.case=TRUE)
data$charity <- wordCounter(data$text, "charity", ignore.case=TRUE)
data$patient <- wordCounter(data$text, "patient", ignore.case=TRUE)
data$hospital <- wordCounter(data$text, "hospital", ignore.case=TRUE)
data$health <- wordCounter(data$text, "health", ignore.case=TRUE)
data$threat <- wordCounter(data$text, "threat", ignore.case=TRUE)
data$damag <- wordCounter(data$text, "damag", ignore.case=TRUE)
data$victim <- wordCounter(data$text, "victim", ignore.case=TRUE)
data$pain <- wordCounter(data$text, "pain", ignore.case=TRUE)
data$harsh <- wordCounter(data$text, "harsh", ignore.case=TRUE)
data$bully <- wordCounter(data$text, "bully", ignore.case=TRUE)
data$abuse <- wordCounter(data$text, "abuse", ignore.case=TRUE)
data$inhuman <- wordCounter(data$text, "inhuman", ignore.case=TRUE)
data$cure <- wordCounter(data$text, "cure", ignore.case=TRUE)
data$vaccine <- wordCounter(data$text, "vaccine", ignore.case=TRUE)
data$parent <- wordCounter(data$text, "parent", ignore.case=TRUE)
familyy <- wordCounter(data$text, "family", ignore.case=TRUE)
families <- wordCounter(data$text, "families", ignore.case=TRUE)
data$families <- familyy+families
data$safe <- wordCounter(data$text, "safe", ignore.case=TRUE)
data$school <- wordCounter(data$text, "school", ignore.case=TRUE)
kid <- wordCounter(data$text, "kid", ignore.case=TRUE)
child <- wordCounter(data$text, "child", ignore.case=TRUE)
data$child <- kid+child
data$smallbusiness <- wordCounter(data$text, "small business", ignore.case=TRUE)
data$unemploy <- wordCounter(data$text, "unemploy", ignore.case=TRUE)
data$prioritize <- wordCounter(data$text, "prioritize", ignore.case=TRUE)
data$community<- wordCounter(data$text, "communit", ignore.case=TRUE)

#fairness
data$oil <- wordCounter(data$text, "oil", ignore.case=TRUE)
data$truth <- wordCounter(data$text, "truth", ignore.case=TRUE)
data$AfricanAmerican <- wordCounter(data$text, "African American", ignore.case=TRUE)
data$foreignInterference <- wordCounter(data$text, "foreign interference", ignore.case=TRUE)
lie <- wordCounter(data$text, "lie", ignore.case=TRUE)
lying <- wordCounter(data$text, "lying", ignore.case=TRUE)
data$lie <- lie+lying
data$fair <- wordCounter(data$text, "fair", ignore.case=TRUE)
data$equity <- wordCounter(data$text, "equit", ignore.case=TRUE)
data$justice <- wordCounter(data$text, "justice", ignore.case=TRUE)
data$impartial <- wordCounter(data$text, "impartial", ignore.case=TRUE)
data$equal <- wordCounter(data$text, "equal", ignore.case=TRUE)
data$proportional <- wordCounter(data$text, "proportional", ignore.case=TRUE)
data$integrity <- wordCounter(data$text, "integrity", ignore.case=TRUE)
data$honest <- wordCounter(data$text, "honest", ignore.case=TRUE)
data$law <- wordCounter(data$text, "law", ignore.case=TRUE)
data$prejudice <- wordCounter(data$text, "prejudice", ignore.case=TRUE)
data$trust <- wordCounter(data$text, "trust", ignore.case=TRUE)
data$justify <- wordCounter(data$text, "justif", ignore.case=TRUE)
data$retaliate <- wordCounter(data$text, "retaliate", ignore.case=TRUE)
data$fraud <- wordCounter(data$text, "fraud", ignore.case=TRUE)
data$cheat <- wordCounter(data$text, "cheat", ignore.case=TRUE)
data$hypocrite <- wordCounter(data$text, "hypocri", ignore.case=TRUE)
data$discriminat <- wordCounter(data$text, "discriminat", ignore.case=TRUE)
data$racism <- wordCounter(data$text, "racism", ignore.case=TRUE)
data$scam <- wordCounter(data$text, "scam", ignore.case=TRUE)
data$liar <- wordCounter(data$text, "liar", ignore.case=TRUE)
data$bias <- wordCounter(data$text, "bias", ignore.case=TRUE)
data$prejudice <- wordCounter(data$text, "prejudice", ignore.case=TRUE)
data$imposter <- wordCounter(data$text, "imposter", ignore.case=TRUE)
data$exploit <- wordCounter(data$text, "exploit", ignore.case=TRUE)
data$betray <- wordCounter(data$text, "betray", ignore.case=TRUE)
data$crook <- wordCounter(data$text, "crook", ignore.case=TRUE)
data$mislead <- wordCounter(data$text, "mislead", ignore.case=TRUE)
data$bigot <- wordCounter(data$text, "bigot", ignore.case=TRUE)
data$sexism <- wordCounter(data$text, "sexism", ignore.case=TRUE)
data$disproportional <- wordCounter(data$text, "disproportion", ignore.case=TRUE)
data$disparity <- wordCounter(data$text, "disparity", ignore.case=TRUE)
mislead <- wordCounter(data$text, "mislead", ignore.case=TRUE)
misled <- wordCounter(data$text, "misled", ignore.case=TRUE)
data$mislead <- mislead+misled
data$dupe <- wordCounter(data$text, "dupe", ignore.case=TRUE)
data$imbalance <- wordCounter(data$text, "imbalance", ignore.case=TRUE)
data$trick <- wordCounter(data$text, "trick", ignore.case=TRUE)
data$rob <- wordCounter(data$text, "rob", ignore.case=TRUE)

#liberty

data$freedom <- wordCounter(data$text, "freedom", ignore.case=TRUE)
data$right <- wordCounter(data$text, "right", ignore.case=TRUE)
data$oppress <- wordCounter(data$text, "oppress", ignore.case=TRUE)
data$restrict <- wordCounter(data$text, "restrict", ignore.case=TRUE)
data$deprive <- wordCounter(data$text, "depriv", ignore.case=TRUE)
data$liberty <- wordCounter(data$text, "libert", ignore.case=TRUE)


#loyalty
data$serve <- wordCounter(data$text, "serve", ignore.case=TRUE)
data$Nation <- wordCounter(data$text, "nation", ignore.case=TRUE)
data$loyal <- wordCounter(data$text, "loyal", ignore.case=TRUE)
data$patriot <- wordCounter(data$text, "patriot", ignore.case=TRUE)
data$follow <- wordCounter(data$text, "follow", ignore.case=TRUE)
data$allegiance <- wordCounter(data$text, "allegiance", ignore.case=TRUE)
data$ally <- wordCounter(data$text, "ally", ignore.case=TRUE)
data$comrade <- wordCounter(data$text, "comrade", ignore.case=TRUE)
data$sacrifice <- wordCounter(data$text, "sacrifice", ignore.case=TRUE)
data$follower <- wordCounter(data$text, "follower", ignore.case=TRUE)
data$unity <- wordCounter(data$text, "unity", ignore.case=TRUE)
data$country <- wordCounter(data$text, "country", ignore.case=TRUE)
data$homeland <- wordCounter(data$text, "homeland", ignore.case=TRUE)
data$solidarity <- wordCounter(data$text, "solidarity", ignore.case=TRUE)
data$community <- wordCounter(data$text, "community", ignore.case=TRUE)
data$wife <- wordCounter(data$text, "wife", ignore.case=TRUE)
data$congregation <- wordCounter(data$text, "congregation", ignore.case=TRUE)
data$belong <- wordCounter(data$text, "belong", ignore.case=TRUE)
data$pledge <- wordCounter(data$text, "pledge", ignore.case=TRUE)
data$together <- wordCounter(data$text, "together", ignore.case=TRUE)
data$traitor <- wordCounter(data$text, "traitor", ignore.case=TRUE)
data$enemy <- wordCounter(data$text, "enem", ignore.case=TRUE)
data$desert <- wordCounter(data$text, "desert", ignore.case=TRUE)
data$faithful <- wordCounter(data$text, "faithful", ignore.case=TRUE)
data$againstUs <- wordCounter(data$text, "against us", ignore.case=TRUE)

#authority
data$presidentTrump <- wordCounter(data$text, "President Trump", ignore.case=TRUE)
obey <- wordCounter(data$text, "obey", ignore.case=TRUE)
obedience <- wordCounter(data$text, "obedience", ignore.case=TRUE)
data$obey <- obey+obedience 
data$authority <- wordCounter(data$text, "authority", ignore.case=TRUE)
data$deference <- wordCounter(data$text, "deference", ignore.case=TRUE)
data$respect <- wordCounter(data$text, "respect", ignore.case=TRUE)
data$tradition <- wordCounter(data$text, "tradition", ignore.case=TRUE)
data$govern <- wordCounter(data$text, "govern", ignore.case=TRUE)
data$honor <- wordCounter(data$text, "honor", ignore.case=TRUE)
data$permit <- wordCounter(data$text, "permi", ignore.case=TRUE)
data$leadership <- wordCounter(data$text, "leadership", ignore.case=TRUE)
data$dictate <- wordCounter(data$text, "dictate", ignore.case=TRUE)
data$duty <- wordCounter(data$text, "duty", ignore.case=TRUE)
comply <- wordCounter(data$text, "comply", ignore.case=TRUE)
compliance <- wordCounter(data$text, "compliance", ignore.case=TRUE)
data$comply <- comply+compliance
police <- wordCounter(data$text, "police", ignore.case=TRUE)
policing <- wordCounter(data$text, "policing", ignore.case=TRUE)
data$police <- police+policing
data$authorize <- wordCounter(data$text, "authoriz", ignore.case=TRUE)
data$control <- wordCounter(data$text, "control", ignore.case=TRUE)
data$command <- wordCounter(data$text, "command", ignore.case=TRUE)
data$subordinate <- wordCounter(data$text, "subordinat", ignore.case=TRUE)
data$punish <- wordCounter(data$text, "punish", ignore.case=TRUE)
data$tradition <- wordCounter(data$text, "tradition", ignore.case=TRUE)
data$fathers <- wordCounter(data$text, "fathers", ignore.case=TRUE)
data$institution <- wordCounter(data$text, "institution", ignore.case=TRUE)
data$governor <- wordCounter(data$text, "governor", ignore.case=TRUE)
data$coerce <- wordCounter(data$text, "coerc", ignore.case=TRUE)
data$inCharge <- wordCounter(data$text, "in charge", ignore.case=TRUE)
data$order <- wordCounter(data$text, "order", ignore.case=TRUE)
data$regulation <- wordCounter(data$text, "regulation", ignore.case=TRUE)
data$submit <- wordCounter(data$text, "submit", ignore.case=TRUE)
data$chaos <- wordCounter(data$text, "chaos", ignore.case=TRUE)
data$treason <- wordCounter(data$text, "treason", ignore.case=TRUE)
data$overthrow <- wordCounter(data$text, "overthrow", ignore.case=TRUE)
data$rebel <- wordCounter(data$text, "rebel", ignore.case=TRUE)
data$treachery <- wordCounter(data$text, "treachery", ignore.case=TRUE)
data$transgress <- wordCounter(data$text, "transgress", ignore.case=TRUE)
data$mutiny<- wordCounter(data$text, "mutiny", ignore.case=TRUE)
data$riot <- wordCounter(data$text, "riot", ignore.case=TRUE)
data$refuse <- wordCounter(data$text, "refuse", ignore.case=TRUE)
data$tumult <- wordCounter(data$text, "tumult", ignore.case=TRUE)
data$overpower <- wordCounter(data$text, "overpower", ignore.case=TRUE)
data$dissent <- wordCounter(data$text, "dissent", ignore.case=TRUE)
data$protest <- wordCounter(data$text, "protest", ignore.case=TRUE)
data$crisis <- wordCounter(data$text, "crisis", ignore.case=TRUE)
data$expert <- wordCounter(data$text, "expert", ignore.case=TRUE)
data$doctor <- wordCounter(data$text, "doctor", ignore.case=TRUE)
data$researcher <- wordCounter(data$text, "researcher", ignore.case=TRUE)

#sanctity
data$worship<-wordCounter(data$text, "worship", ignore.case=TRUE)
data$church<-wordCounter(data$text, "church", ignore.case=TRUE)
data$god<-wordCounter(data$text, "god", ignore.case=TRUE)
data$pray<-wordCounter(data$text, "pray", ignore.case=TRUE)
data$sanctity <- wordCounter(data$text, "sanctity", ignore.case=TRUE)
data$sacred <- wordCounter(data$text, "sacred", ignore.case=TRUE)
pure<- wordCounter(data$text, "pure", ignore.case=TRUE)
purity <- wordCounter(data$text, "purity", ignore.case=TRUE)
data$pure <- pure+purity
data$wholesome <- wordCounter(data$text, "wholesome", ignore.case=TRUE)
data$dignity <- wordCounter(data$text, "dignity", ignore.case=TRUE)
data$holy <- wordCounter(data$text, "holy", ignore.case=TRUE)
data$pious <- wordCounter(data$text, "pious", ignore.case=TRUE)
data$righteous <- wordCounter(data$text, "righteous", ignore.case=TRUE)
data$spiritual <- wordCounter(data$text, "spiritual", ignore.case=TRUE)
data$biblical <- wordCounter(data$text, "biblical", ignore.case=TRUE)
data$noble <- wordCounter(data$text, "noble", ignore.case=TRUE)
data$religion <- wordCounter(data$text, "religion", ignore.case=TRUE)
data$soul <- wordCounter(data$text, "soul", ignore.case=TRUE)
data$catholic <- wordCounter(data$text, "catholic", ignore.case=TRUE)
data$heaven <- wordCounter(data$text, "heaven", ignore.case=TRUE)
data$bless <- wordCounter(data$text, "bless", ignore.case=TRUE)
data$christian <- wordCounter(data$text, "christian", ignore.case=TRUE)
data$atone <- wordCounter(data$text, "atone", ignore.case=TRUE)
data$glory <- wordCounter(data$text, "glory", ignore.case=TRUE)
data$almighty <- wordCounter(data$text, "almighty", ignore.case=TRUE)
data$lord <- wordCounter(data$text, "lord", ignore.case=TRUE)
data$clean <- wordCounter(data$text, "clean", ignore.case=TRUE)
data$refine <- wordCounter(data$text, "refine", ignore.case=TRUE)
data$degradation <- wordCounter(data$text, "degrad", ignore.case=TRUE)
data$repulsive <- wordCounter(data$text, "repulsive", ignore.case=TRUE)
data$sin <- wordCounter(data$text, "sin", ignore.case=TRUE)
data$disgust<-wordCounter(data$text, "disgust", ignore.case=TRUE)
data$corrupt <- wordCounter(data$text, "corrupt", ignore.case=TRUE)
data$horrify <- wordCounter(data$text, "horrify", ignore.case=TRUE)
data$horror <- wordCounter(data$text, "horror", ignore.case=TRUE)
data$obscene <- wordCounter(data$text, "obscene", ignore.case=TRUE)
data$swear <- wordCounter(data$text, "swear", ignore.case=TRUE)
data$spoil <- wordCounter(data$text, "spoil", ignore.case=TRUE)
data$foul <- wordCounter(data$text, "foul", ignore.case=TRUE)
data$waste <- wordCounter(data$text, "wast", ignore.case=TRUE)
data$partisan <- wordCounter(data$text, "partisan", ignore.case=TRUE)
data$trash <- wordCounter(data$text, "trash", ignore.case=TRUE)
data$china<-wordCounter(data$text, "china", ignore.case=TRUE)
data$chinese<-wordCounter(data$text, "chinese", ignore.case=TRUE)
data$pelosi <-wordCounter(data$text, "pelosi", ignore.case=TRUE)
data$trump<- wordCounter(data$text, "trump", ignore.case=TRUE)
data$obama<- wordCounter(data$text, "Obama", ignore.case=TRUE)
data$environment<-wordCounter(data$text, "environment", ignore.case=TRUE)
data$russia<-wordCounter(data$text, "russia", ignore.case=TRUE)
data$ukraine<-wordCounter(data$text, "ukrain", ignore.case=TRUE)
data$dictator<-wordCounter(data$text, "dictator", ignore.case=TRUE)
data$communism<-wordCounter(data$text, "communis", ignore.case=TRUE)

#extra category (framing?)
data$covid <- wordCounter(data$text, "covid", ignore.case=TRUE)
data$corona <- wordCounter(data$text, "corona", ignore.case=TRUE)
data$act <- wordCounter(data$text, "act", ignore.case=TRUE)
data$bill <- wordCounter(data$text, "bill", ignore.case=TRUE)
data$proposal <- wordCounter(data$text, "proposal", ignore.case=TRUE)
#------------------------keyword end----------------------------------------------

#First we run a regression on all of the data
dataRegress<- data[,13:216]
dataRegress$party <- as.factor(dataRegress$party)

#This is the model fit on all of the data.  You use this in order to see how accurate your word predictions were
model <- glm(formula = party ~ ., family=binomial(link="logit"), data= dataRegress)
#To see the stats table, run this line
summary(model)

#We run a regression.  Choose the training set for machine learning application
accuracy=numeric(10)
for(i in 1:10){
  
trainSize=2/3*length(dataRegress[,1]) #how many do we want to train on
in.train<- sample(nrow(dataRegress), size=trainSize)
trainData <- dataRegress[ in.train,] # The data that we will train on
testData <- dataRegress[ -in.train, ] #The data that we will test on
mod<- glm(formula = party ~ ., family=binomial(link="logit"), data= testData)
prediction <-  predict(mod, testData, type="response") #Predict the test data that we set aside
prediction <- prediction>0.5
loss = sum((as.integer(testData$party)-as.integer(prediction)-1)^2)
accuracy[i]=1-loss/length(prediction)
}
mean(accuracy)

